//! Build script: parses the 14 vendored Adobe Core 14 AFM files with
//! the `adobe-font-metrics` crate and code-generates `$OUT_DIR/baked.rs`,
//! a single Rust file containing one
//! `static <FONT>: FontMetrics<'static>` per Core 14
//! face plus a per-Latin-font `[Option<f32>; 256]`
//! `WinAnsiEncoding` width table.
//!
//! The byte→`char` `WinAnsi` map lives in `src/winansi_char_map.rs`
//! as a hand-transcribed const, not derived here; the build script
//! intentionally has no Adobe Glyph List dependency so the published
//! crate doesn't carry a BSD-3-Clause data file.
//!
//! Generated code is **clippy-clean by construction** (no `#[allow]`s)
//! against the workspace's pedantic/nursery/restriction lint set:
//! - All numeric literals carry an explicit `_f32` suffix to defuse
//!   `clippy::lossy_float_literal` / `clippy::excessive_precision`.
//! - Floats are formatted with `{:?}`, which prints the shortest
//!   round-trippable representation.
//! - Struct fields are emitted in declaration order to satisfy
//!   `clippy::inconsistent_struct_constructor`.
//! - Names are `SCREAMING_SNAKE_CASE`; no `pub`, no field shorthand,
//!   no `use` statements inside the generated file.
//! - The generated statics are `const`/`static` items in the crate
//!   root via `include!`, so `BBox`, `CharacterMetric`, `FontMetrics`,
//!   `KerningPair`, and `Cow` must all be in scope at the include
//!   site: `src/lib.rs` arranges that.
//!
//! The build script avoids `unwrap`, `expect`, `panic!`, and the
//! `println!`/`eprintln!` macros (all `clippy::restriction` group
//! lints enabled at the workspace level) by returning `Result` from
//! `main` and writing Cargo directives with `writeln!` on a locked
//! stdout handle.

use adobe_font_metrics::{
    BBox, CharacterCode, Direction, FontMetrics, KerningOperands, MetricsSets, RecordContext,
    Vector, parse,
};

use std::error::Error;
use std::fmt::Write as _;
use std::fs;
use std::io::{self, Write as _};
use std::path::PathBuf;

// Bring the canonical PDF WinAnsiEncoding table into scope. The same
// file is `mod`-included by `src/lib.rs` at runtime: single source
// of truth, see `src/winansi_table.rs`.
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/winansi_table.rs"));

/// One `(rust_const_ident, afm_file_name, is_latin)` row per Core 14 face.
/// `is_latin = false` for `Symbol` and `ZapfDingbats`, which don't use
/// `WinAnsi` and therefore get no per-font width table.
const FONTS: &[(&str, &str, bool)] = &[
    ("HELVETICA", "Helvetica.afm", true),
    ("HELVETICA_BOLD", "Helvetica-Bold.afm", true),
    ("HELVETICA_OBLIQUE", "Helvetica-Oblique.afm", true),
    ("HELVETICA_BOLDOBLIQUE", "Helvetica-BoldOblique.afm", true),
    ("TIMES_ROMAN", "Times-Roman.afm", true),
    ("TIMES_BOLD", "Times-Bold.afm", true),
    ("TIMES_ITALIC", "Times-Italic.afm", true),
    ("TIMES_BOLDITALIC", "Times-BoldItalic.afm", true),
    ("COURIER", "Courier.afm", true),
    ("COURIER_BOLD", "Courier-Bold.afm", true),
    ("COURIER_OBLIQUE", "Courier-Oblique.afm", true),
    ("COURIER_BOLDOBLIQUE", "Courier-BoldOblique.afm", true),
    ("SYMBOL", "Symbol.afm", false),
    ("ZAPFDINGBATS", "ZapfDingbats.afm", false),
];

fn main() -> Result<(), Box<dyn Error>> {
    let manifest_dir: PathBuf = std::env::var_os("CARGO_MANIFEST_DIR")
        .ok_or("CARGO_MANIFEST_DIR not set")?
        .into();
    let out_dir: PathBuf = std::env::var_os("OUT_DIR").ok_or("OUT_DIR not set")?.into();

    // Write Cargo directives via locked stdout to avoid `clippy::print_stdout`
    // on `println!` while still producing the exact bytes Cargo expects.
    let stdout = io::stdout();
    let mut stdout = stdout.lock();
    // Re-run if this script, the WinAnsi glyph-name table, or any of the
    // 14 vendored AFM files changes.
    writeln!(stdout, "cargo:rerun-if-changed=build.rs")?;
    writeln!(stdout, "cargo:rerun-if-changed=src/winansi_table.rs")?;
    for (_, file, _) in FONTS {
        writeln!(stdout, "cargo:rerun-if-changed=data/afm/{file}")?;
    }
    drop(stdout);

    let mut buf = String::new();
    buf.push_str("// @generated by pdf-base14-metrics/build.rs: DO NOT EDIT BY HAND.\n\n");

    for (const_ident, file, is_latin) in FONTS {
        let path = manifest_dir.join("data").join("afm").join(file);
        let src = fs::read_to_string(&path).map_err(|e| format!("read {}: {e}", path.display()))?;
        let metrics = parse(&src).map_err(|e| format!("parse {}: {e}", path.display()))?;
        emit_font(&mut buf, const_ident, &metrics, *is_latin)?;
    }

    fs::write(out_dir.join("baked.rs"), buf)?;
    Ok(())
}

/// Emits an f32 literal with an `_f32` suffix, using the shortest
/// round-trippable decimal representation. Special-cases `0.0` /
/// `-0.0` so signed zero round-trips deterministically.
fn emit_f32(buf: &mut String, v: f32) -> Result<(), std::fmt::Error> {
    if v == 0.0_f32 {
        // `{:?}` on signed zero prints "-0.0" / "0.0" already, but
        // routing through this branch keeps the suffix attachment
        // consistent regardless of formatter behaviour.
        if v.is_sign_negative() {
            return write!(buf, "-0.0_f32");
        }
        return write!(buf, "0.0_f32");
    }
    // `{:?}` always produces a decimal point or exponent for finite
    // non-zero f32, so `_f32` attaches to a valid float literal.
    // Emit a unary minus directly so option arguments remain warning-free.
    if v.is_sign_negative() {
        write!(buf, "-{:?}_f32", -v)
    } else {
        write!(buf, "{v:?}_f32")
    }
}

/// Emits a `"..."` string literal with `\` and `"` escaped. AFM glyph
/// names and family names are restricted to ASCII identifiers in
/// practice; the escaping is defensive against any odd character
/// that might appear in `FullName`/`Weight`/`EncodingScheme`.
fn emit_str_literal(buf: &mut String, s: &str) -> Result<(), std::fmt::Error> {
    buf.push('"');
    for ch in s.chars() {
        match ch {
            '\\' => buf.push_str("\\\\"),
            '"' => buf.push_str("\\\""),
            '\n' => buf.push_str("\\n"),
            '\r' => buf.push_str("\\r"),
            '\t' => buf.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                write!(buf, "\\u{{{:x}}}", c as u32)?;
            }
            c => buf.push(c),
        }
    }
    buf.push('"');
    Ok(())
}

fn emit_option<T>(
    buf: &mut String,
    value: Option<T>,
    emit: impl FnOnce(&mut String, T) -> std::fmt::Result,
) -> std::fmt::Result {
    match value {
        Some(value) => {
            buf.push_str("Some(");
            emit(buf, value)?;
            buf.push(')');
        }
        None => buf.push_str("None"),
    }
    Ok(())
}

fn emit_cow(buf: &mut String, value: &str) -> std::fmt::Result {
    buf.push_str("Cow::Borrowed(");
    emit_str_literal(buf, value)?;
    buf.push(')');
    Ok(())
}

fn emit_vector(buf: &mut String, value: Vector) -> std::fmt::Result {
    buf.push_str("Vector { x: ");
    emit_f32(buf, value.x)?;
    buf.push_str(", y: ");
    emit_f32(buf, value.y)?;
    buf.push_str(" }");
    Ok(())
}

fn emit_bbox(buf: &mut String, value: BBox) -> std::fmt::Result {
    buf.push_str("BBox { llx: ");
    emit_f32(buf, value.llx)?;
    buf.push_str(", lly: ");
    emit_f32(buf, value.lly)?;
    buf.push_str(", urx: ");
    emit_f32(buf, value.urx)?;
    buf.push_str(", ury: ");
    emit_f32(buf, value.ury)?;
    buf.push_str(" }");
    Ok(())
}

fn emit_direction(buf: &mut String, value: Direction) -> std::fmt::Result {
    write!(buf, "Direction::{value:?}")
}

fn emit_sets(buf: &mut String, value: MetricsSets) -> std::fmt::Result {
    write!(buf, "MetricsSets::{value:?}")
}

fn emit_bool(buf: &mut String, value: bool) -> std::fmt::Result {
    write!(buf, "{value}")
}
fn emit_u32(buf: &mut String, value: u32) -> std::fmt::Result {
    write!(buf, "{value}_u32")
}
fn emit_u8(buf: &mut String, value: u8) -> std::fmt::Result {
    write!(buf, "{value}_u8")
}

fn emit_code(buf: &mut String, value: &CharacterCode<'_>) -> std::fmt::Result {
    match value {
        CharacterCode::Decimal(code) => write!(buf, "CharacterCode::Decimal({code}_i32)"),
        CharacterCode::Hex(hex) => {
            buf.push_str("CharacterCode::Hex(");
            emit_cow(buf, hex)?;
            buf.push(')');
            Ok(())
        }
    }
}

fn emit_character_metrics(buf: &mut String, ident: &str, m: &FontMetrics<'_>) -> std::fmt::Result {
    writeln!(buf, "const {ident}_CHARS: &[CharacterMetric<'static>] = &[")?;
    for c in m.character_metrics.iter() {
        buf.push_str("CharacterMetric { code: ");
        emit_code(buf, &c.code)?;
        buf.push_str(", name: ");
        emit_option(buf, c.name.as_deref(), emit_cow)?;
        buf.push_str(", advances: [");
        for advance in c.advances {
            emit_option(buf, advance, emit_vector)?;
            buf.push(',');
        }
        buf.push_str("], bbox: ");
        emit_option(buf, c.bbox, emit_bbox)?;
        buf.push_str(", v_vector: ");
        emit_option(buf, c.v_vector, emit_vector)?;
        buf.push_str(", ligatures: Cow::Borrowed(&[");
        for ligature in c.ligatures.iter() {
            buf.push_str("Ligature { successor: ");
            emit_cow(buf, &ligature.successor)?;
            buf.push_str(", ligature: ");
            emit_cow(buf, &ligature.ligature)?;
            buf.push_str(" },");
        }
        buf.push_str("]) },\n");
    }
    buf.push_str("];\n");
    Ok(())
}

fn emit_kerning_pairs(buf: &mut String, ident: &str, m: &FontMetrics<'_>) -> std::fmt::Result {
    writeln!(buf, "const {ident}_KERNS: &[KerningPair<'static>] = &[")?;
    for pair in m.kerning_pairs.iter() {
        let (kind, left, right) = match &pair.operands {
            KerningOperands::Names { left, right } => ("Names", left, right),
            KerningOperands::Hex { left, right } => ("Hex", left, right),
        };
        write!(
            buf,
            "KerningPair {{ operands: KerningOperands::{kind} {{ left: "
        )?;
        emit_cow(buf, left)?;
        buf.push_str(", right: ");
        emit_cow(buf, right)?;
        buf.push_str(" }, adjustment: ");
        emit_vector(buf, pair.adjustment)?;
        buf.push_str(", direction: ");
        emit_direction(buf, pair.direction)?;
        buf.push_str(" },\n");
    }
    buf.push_str("];\n");
    Ok(())
}

fn emit_context(buf: &mut String, value: RecordContext) -> std::fmt::Result {
    buf.push_str("RecordContext::");
    match value {
        RecordContext::Direction(sets) => {
            buf.push_str("Direction(");
            emit_sets(buf, sets)?;
            buf.push(')');
        }
        RecordContext::KernPairs(direction) => {
            buf.push_str("KernPairs(");
            emit_direction(buf, direction)?;
            buf.push(')');
        }
        other => write!(buf, "{other:?}")?,
    }
    Ok(())
}

fn emit_auxiliary(buf: &mut String, ident: &str, m: &FontMetrics<'_>) -> std::fmt::Result {
    writeln!(buf, "const {ident}_TRACKS: &[TrackKern] = &[")?;
    for track in m.track_kerns.iter() {
        write!(
            buf,
            "TrackKern {{ degree: {}_i32, min_point_size: ",
            track.degree
        )?;
        emit_f32(buf, track.min_point_size)?;
        buf.push_str(", min_kern: ");
        emit_f32(buf, track.min_kern)?;
        buf.push_str(", max_point_size: ");
        emit_f32(buf, track.max_point_size)?;
        buf.push_str(", max_kern: ");
        emit_f32(buf, track.max_kern)?;
        buf.push_str(" },\n");
    }
    buf.push_str("];\n");
    writeln!(buf, "const {ident}_COMPOSITES: &[Composite<'static>] = &[")?;
    for composite in m.composites.iter() {
        buf.push_str("Composite { name: ");
        emit_cow(buf, &composite.name)?;
        buf.push_str(", components: Cow::Borrowed(&[");
        for component in composite.components.iter() {
            buf.push_str("CompositeComponent { name: ");
            emit_cow(buf, &component.name)?;
            buf.push_str(", offset: ");
            emit_vector(buf, component.offset)?;
            buf.push_str(" },");
        }
        buf.push_str("]) },\n");
    }
    buf.push_str("];\n");
    writeln!(buf, "const {ident}_RECORDS: &[SourceRecord<'static>] = &[")?;
    for record in m.source_records.iter() {
        write!(buf, "SourceRecord {{ line: {}, context: ", record.line)?;
        emit_context(buf, record.context)?;
        buf.push_str(", keyword: ");
        emit_cow(buf, &record.keyword)?;
        buf.push_str(", value: ");
        emit_cow(buf, &record.value)?;
        buf.push_str(" },\n");
    }
    buf.push_str("];\n");
    Ok(())
}

fn emit_latin_tables(
    buf: &mut String,
    ident: &str,
    m: &FontMetrics<'_>,
) -> Result<(), Box<dyn Error>> {
    writeln!(buf, "const {ident}_WINANSI: [Option<f32>; 256] = [")?;
    for name in WINANSI_TABLE {
        let width = name
            .and_then(|name| {
                m.character_metrics
                    .iter()
                    .find(|c| c.name.as_deref() == Some(name))
            })
            .and_then(|c| m.advance(c, Direction::Zero))
            .map(|v| v.x);
        emit_option(buf, width, emit_f32)?;
        buf.push_str(",\n");
    }
    buf.push_str("];\n");
    let mut pairs: Vec<_> = m
        .character_metrics
        .iter()
        .filter_map(|c| Some((c.name.as_deref()?, m.advance(c, Direction::Zero)?.x)))
        .collect();
    pairs.sort_by_key(|(name, _)| *name);
    for pair in pairs.windows(2) {
        if pair[0].0 == pair[1].0 {
            return Err(format!("duplicate glyph name {:?} in {ident} AFM", pair[0].0).into());
        }
    }
    writeln!(buf, "const {ident}_NAME_WIDTHS: &[(&str, f32)] = &[")?;
    for (name, width) in pairs {
        buf.push('(');
        emit_str_literal(buf, name)?;
        buf.push(',');
        emit_f32(buf, width)?;
        buf.push_str("),\n");
    }
    buf.push_str("];\n");
    Ok(())
}

fn emit_font(
    buf: &mut String,
    ident: &str,
    m: &FontMetrics<'_>,
    is_latin: bool,
) -> Result<(), Box<dyn Error>> {
    emit_character_metrics(buf, ident, m)?;
    emit_kerning_pairs(buf, ident, m)?;
    emit_auxiliary(buf, ident, m)?;
    if is_latin {
        emit_latin_tables(buf, ident, m)?;
    }
    emit_font_static(buf, ident, m)?;
    Ok(())
}

fn emit_font_static(buf: &mut String, ident: &str, m: &FontMetrics<'_>) -> std::fmt::Result {
    writeln!(buf, "static {ident}: FontMetrics<'static> = FontMetrics {{")?;
    buf.push_str("afm_version: ");
    emit_cow(buf, &m.afm_version)?;
    buf.push_str(",\n");
    buf.push_str("font_name: ");
    emit_cow(buf, &m.font_name)?;
    buf.push_str(",\n");
    buf.push_str("font_bbox: ");
    emit_bbox(buf, m.font_bbox)?;
    buf.push_str(",\n");
    buf.push_str("metrics_sets: ");
    emit_option(buf, m.metrics_sets, emit_sets)?;
    buf.push_str(",\n");
    buf.push_str("full_name: ");
    emit_option(buf, m.full_name.as_deref(), emit_cow)?;
    buf.push_str(",\n");
    buf.push_str("family_name: ");
    emit_option(buf, m.family_name.as_deref(), emit_cow)?;
    buf.push_str(",\n");
    buf.push_str("weight: ");
    emit_option(buf, m.weight.as_deref(), emit_cow)?;
    buf.push_str(",\n");
    buf.push_str("version: ");
    emit_option(buf, m.version.as_deref(), emit_cow)?;
    buf.push_str(",\n");
    buf.push_str("notice: ");
    emit_option(buf, m.notice.as_deref(), emit_cow)?;
    buf.push_str(",\n");
    buf.push_str("encoding_scheme: ");
    emit_option(buf, m.encoding_scheme.as_deref(), emit_cow)?;
    buf.push_str(",\n");
    buf.push_str("character_set: ");
    emit_option(buf, m.character_set.as_deref(), emit_cow)?;
    buf.push_str(",\n");
    buf.push_str("mapping_scheme: ");
    emit_option(buf, m.mapping_scheme, emit_u32)?;
    buf.push_str(",\n");
    buf.push_str("esc_char: ");
    emit_option(buf, m.esc_char, emit_u8)?;
    buf.push_str(",\n");
    buf.push_str("characters: ");
    emit_option(buf, m.characters, emit_u32)?;
    buf.push_str(",\n");
    buf.push_str("is_base_font: ");
    emit_option(buf, m.is_base_font, emit_bool)?;
    buf.push_str(",\n");
    buf.push_str("is_cid_font: ");
    emit_option(buf, m.is_cid_font, emit_bool)?;
    buf.push_str(",\n");
    buf.push_str("v_vector: ");
    emit_option(buf, m.v_vector, emit_vector)?;
    buf.push_str(",\n");
    buf.push_str("is_fixed_v: ");
    emit_option(buf, m.is_fixed_v, emit_bool)?;
    buf.push_str(",\n");
    buf.push_str("cap_height: ");
    emit_option(buf, m.cap_height, emit_f32)?;
    buf.push_str(",\n");
    buf.push_str("x_height: ");
    emit_option(buf, m.x_height, emit_f32)?;
    buf.push_str(",\n");
    buf.push_str("ascender: ");
    emit_option(buf, m.ascender, emit_f32)?;
    buf.push_str(",\n");
    buf.push_str("descender: ");
    emit_option(buf, m.descender, emit_f32)?;
    buf.push_str(",\n");
    buf.push_str("std_hw: ");
    emit_option(buf, m.std_hw, emit_f32)?;
    buf.push_str(",\n");
    buf.push_str("std_vw: ");
    emit_option(buf, m.std_vw, emit_f32)?;
    buf.push_str(",\n");
    buf.push_str("directions: [");
    for direction in &m.directions {
        buf.push_str("DirectionMetrics { underline_position: ");
        emit_option(buf, direction.underline_position, emit_f32)?;
        buf.push_str(", underline_thickness: ");
        emit_option(buf, direction.underline_thickness, emit_f32)?;
        buf.push_str(", italic_angle: ");
        emit_option(buf, direction.italic_angle, emit_f32)?;
        buf.push_str(", char_width: ");
        emit_option(buf, direction.char_width, emit_vector)?;
        buf.push_str(", is_fixed_pitch: ");
        emit_option(buf, direction.is_fixed_pitch, emit_bool)?;
        buf.push_str(" },");
    }
    buf.push_str("],\n");
    writeln!(buf, "character_metrics: Cow::Borrowed({ident}_CHARS),")?;
    writeln!(buf, "kerning_pairs: Cow::Borrowed({ident}_KERNS),")?;
    writeln!(buf, "track_kerns: Cow::Borrowed({ident}_TRACKS),")?;
    writeln!(buf, "composites: Cow::Borrowed({ident}_COMPOSITES),")?;
    writeln!(buf, "source_records: Cow::Borrowed({ident}_RECORDS),")?;
    buf.push_str("};\n");
    Ok(())
}
