//! Build script: parses the 14 vendored Adobe Core 14 AFM files with
//! the `adobe-font-metrics` crate and code-generates `$OUT_DIR/baked.rs`,
//! a single Rust file containing one
//! `static <FONT>: adobe_font_metrics::FontMetrics<'static>` per Core 14
//! face plus a per-Latin-font `[Option<f32>; 256]`
//! `WinAnsiEncoding` width table.
//!
//! The byte→`char` `WinAnsi` map lives in `src/winansi_char_map.rs`
//! as a hand-transcribed const, not derived here — the build script
//! intentionally has no Adobe Glyph List dependency so the published
//! crate doesn't carry a BSD-3-Clause data file.
//!
//! Generated code is **clippy-clean by construction** (no `#[allow]`s)
//! against the workspace's pedantic/nursery/restriction lint set:
//! - All numeric literals carry an explicit `_f32` suffix to defuse
//!   `clippy::lossy_float_literal` / `clippy::excessive_precision`.
//! - Floats are formatted with `{:?}`, which prints the shortest
//!   round-trippable representation.
//! - Struct fields are emitted in declaration order to satisfy
//!   `clippy::inconsistent_struct_constructor`.
//! - Names are `SCREAMING_SNAKE_CASE`; no `pub`, no field shorthand,
//!   no `use` statements inside the generated file.
//! - The generated statics are `const`/`static` items in the crate
//!   root via `include!`, so `BBox`, `CharacterMetric`, `FontMetrics`,
//!   `KerningPair`, and `Cow` must all be in scope at the include
//!   site — `src/lib.rs` arranges that.
//!
//! The build script avoids `unwrap`, `expect`, `panic!`, and the
//! `println!`/`eprintln!` macros (all `clippy::restriction` group
//! lints enabled at the workspace level) by returning `Result` from
//! `main` and writing Cargo directives with `writeln!` on a locked
//! stdout handle.

use std::error::Error;
use std::fmt::Write as _;
use std::fs;
use std::io::{self, Write as _};
use std::path::PathBuf;

// Bring the canonical PDF WinAnsiEncoding table into scope. The same
// file is `mod`-included by `src/lib.rs` at runtime — single source
// of truth, see `src/winansi_table.rs`.
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/winansi_table.rs"));

/// One `(rust_const_ident, afm_file_name, is_latin)` row per Core 14 face.
/// `is_latin = false` for `Symbol` and `ZapfDingbats`, which don't use
/// `WinAnsi` and therefore get no per-font width table.
const FONTS: &[(&str, &str, bool)] = &[
    ("HELVETICA", "Helvetica.afm", true),
    ("HELVETICA_BOLD", "Helvetica-Bold.afm", true),
    ("HELVETICA_OBLIQUE", "Helvetica-Oblique.afm", true),
    ("HELVETICA_BOLDOBLIQUE", "Helvetica-BoldOblique.afm", true),
    ("TIMES_ROMAN", "Times-Roman.afm", true),
    ("TIMES_BOLD", "Times-Bold.afm", true),
    ("TIMES_ITALIC", "Times-Italic.afm", true),
    ("TIMES_BOLDITALIC", "Times-BoldItalic.afm", true),
    ("COURIER", "Courier.afm", true),
    ("COURIER_BOLD", "Courier-Bold.afm", true),
    ("COURIER_OBLIQUE", "Courier-Oblique.afm", true),
    ("COURIER_BOLDOBLIQUE", "Courier-BoldOblique.afm", true),
    ("SYMBOL", "Symbol.afm", false),
    ("ZAPFDINGBATS", "ZapfDingbats.afm", false),
];

fn main() -> Result<(), Box<dyn Error>> {
    let manifest_dir: PathBuf = std::env::var_os("CARGO_MANIFEST_DIR")
        .ok_or("CARGO_MANIFEST_DIR not set")?
        .into();
    let out_dir: PathBuf = std::env::var_os("OUT_DIR").ok_or("OUT_DIR not set")?.into();

    // Write Cargo directives via locked stdout — avoids `clippy::print_stdout`
    // on `println!` while still producing the exact bytes Cargo expects.
    let stdout = io::stdout();
    let mut stdout = stdout.lock();
    // Re-run if this script, the WinAnsi glyph-name table, or any of the
    // 14 vendored AFM files changes.
    writeln!(stdout, "cargo:rerun-if-changed=build.rs")?;
    writeln!(stdout, "cargo:rerun-if-changed=src/winansi_table.rs")?;
    for (_, file, _) in FONTS {
        writeln!(stdout, "cargo:rerun-if-changed=data/afm/{file}")?;
    }
    drop(stdout);

    let mut buf = String::new();
    buf.push_str("// @generated by pdf-base14-metrics/build.rs — DO NOT EDIT BY HAND.\n\n");

    for (const_ident, file, is_latin) in FONTS {
        let path = manifest_dir.join("data").join("afm").join(file);
        let src = fs::read_to_string(&path).map_err(|e| format!("read {}: {e}", path.display()))?;
        let metrics = adobe_font_metrics::parse(&src)
            .map_err(|e| format!("parse {}: {e}", path.display()))?;
        emit_font(&mut buf, const_ident, &metrics, *is_latin)?;
    }

    fs::write(out_dir.join("baked.rs"), buf)?;
    Ok(())
}

fn emit_font(
    buf: &mut String,
    ident: &str,
    m: &adobe_font_metrics::FontMetrics<'_>,
    is_latin: bool,
) -> Result<(), Box<dyn Error>> {
    // Per-glyph metrics → its own const array, referenced by the main static.
    writeln!(buf, "const {ident}_CHARS: &[CharacterMetric<'static>] = &[")?;
    for c in m.character_metrics.iter() {
        write!(buf, "    CharacterMetric {{ code: ")?;
        write!(buf, "{}_i32", c.code)?;
        write!(buf, ", name: Cow::Borrowed(")?;
        emit_str_literal(buf, &c.name)?;
        write!(buf, "), width_x: ")?;
        emit_f32(buf, c.width_x)?;
        write!(buf, ", bbox: ")?;
        match c.bbox {
            Some(bb) => {
                write!(buf, "Some(BBox {{ llx: ")?;
                emit_f32(buf, bb.llx)?;
                write!(buf, ", lly: ")?;
                emit_f32(buf, bb.lly)?;
                write!(buf, ", urx: ")?;
                emit_f32(buf, bb.urx)?;
                write!(buf, ", ury: ")?;
                emit_f32(buf, bb.ury)?;
                write!(buf, " }})")?;
            }
            None => write!(buf, "None")?,
        }
        writeln!(buf, " }},")?;
    }
    writeln!(buf, "];\n")?;

    // Kerning pairs → another const array.
    writeln!(buf, "const {ident}_KERNS: &[KerningPair<'static>] = &[")?;
    for k in m.kerning_pairs.iter() {
        write!(buf, "    KerningPair {{ left: Cow::Borrowed(")?;
        emit_str_literal(buf, &k.left)?;
        write!(buf, "), right: Cow::Borrowed(")?;
        emit_str_literal(buf, &k.right)?;
        write!(buf, "), adjust: ")?;
        emit_f32(buf, k.adjust)?;
        writeln!(buf, " }},")?;
    }
    writeln!(buf, "];\n")?;

    // Optional per-font WinAnsi width table (Latin faces only).
    if is_latin {
        writeln!(buf, "const {ident}_WINANSI: [Option<f32>; 256] = [")?;
        for entry in &WINANSI_TABLE {
            match entry {
                Some(name) => match find_width(m, name) {
                    Some(w) => {
                        write!(buf, "    Some(")?;
                        emit_f32(buf, w)?;
                        writeln!(buf, "),")?;
                    }
                    None => writeln!(buf, "    None,")?,
                },
                None => writeln!(buf, "    None,")?,
            }
        }
        writeln!(buf, "];\n")?;

        // Sorted `(glyph_name, width)` index for O(log n) by-name
        // lookup. The AFM `CharacterMetric` slice above is in file
        // order (= the AFM `C ...` line order, not sorted), so a
        // binary search would be unsound against it. Pull the name +
        // width into a parallel sorted slice — small (~315 entries
        // × 16 bytes ≈ 5 KB per face), and `glyph_width_by_name` is
        // on the encoder hot path (called once per non-WinAnsi char
        // in a document during PDF emit).
        let mut pairs: Vec<(&str, f32)> = m
            .character_metrics
            .iter()
            .map(|c| (c.name.as_ref(), c.width_x))
            .collect();
        pairs.sort_by(|a, b| a.0.cmp(b.0));
        // Defensive: AFM should never define the same glyph twice,
        // but a duplicate would silently shadow during binary search.
        // We dedup on name and treat any collision as a build-time
        // error so we never paper over it.
        for w in pairs.windows(2) {
            if w[0].0 == w[1].0 {
                return Err(format!("duplicate glyph name {:?} in {ident} AFM", w[0].0).into());
            }
        }
        // Const items already imply `'static` for inner references, so we
        // omit the explicit lifetime to keep generated code clippy-clean
        // under `clippy::redundant_static_lifetimes`.
        writeln!(buf, "const {ident}_NAME_WIDTHS: &[(&str, f32)] = &[")?;
        for (name, w) in &pairs {
            write!(buf, "    (")?;
            emit_str_literal(buf, name)?;
            write!(buf, ", ")?;
            emit_f32(buf, *w)?;
            writeln!(buf, "),")?;
        }
        writeln!(buf, "];\n")?;
    }

    // The main static. Field order matches `adobe_font_metrics::FontMetrics`'s
    // declaration order (`clippy::inconsistent_struct_constructor`).
    writeln!(buf, "static {ident}: FontMetrics<'static> = FontMetrics {{")?;

    write!(buf, "    font_name: Cow::Borrowed(")?;
    emit_str_literal(buf, &m.font_name)?;
    writeln!(buf, "),")?;

    write!(buf, "    full_name: Cow::Borrowed(")?;
    emit_str_literal(buf, &m.full_name)?;
    writeln!(buf, "),")?;

    write!(buf, "    family_name: Cow::Borrowed(")?;
    emit_str_literal(buf, &m.family_name)?;
    writeln!(buf, "),")?;

    write!(buf, "    weight: Cow::Borrowed(")?;
    emit_str_literal(buf, &m.weight)?;
    writeln!(buf, "),")?;

    write!(buf, "    italic_angle: ")?;
    emit_f32(buf, m.italic_angle)?;
    writeln!(buf, ",")?;

    writeln!(buf, "    is_fixed_pitch: {},", m.is_fixed_pitch)?;

    write!(buf, "    font_bbox: BBox {{ llx: ")?;
    emit_f32(buf, m.font_bbox.llx)?;
    write!(buf, ", lly: ")?;
    emit_f32(buf, m.font_bbox.lly)?;
    write!(buf, ", urx: ")?;
    emit_f32(buf, m.font_bbox.urx)?;
    write!(buf, ", ury: ")?;
    emit_f32(buf, m.font_bbox.ury)?;
    writeln!(buf, " }},")?;

    write!(buf, "    underline_position: ")?;
    emit_f32(buf, m.underline_position)?;
    writeln!(buf, ",")?;

    write!(buf, "    underline_thickness: ")?;
    emit_f32(buf, m.underline_thickness)?;
    writeln!(buf, ",")?;

    write!(buf, "    cap_height: ")?;
    emit_f32(buf, m.cap_height)?;
    writeln!(buf, ",")?;

    write!(buf, "    x_height: ")?;
    emit_f32(buf, m.x_height)?;
    writeln!(buf, ",")?;

    write!(buf, "    ascender: ")?;
    emit_f32(buf, m.ascender)?;
    writeln!(buf, ",")?;

    write!(buf, "    descender: ")?;
    emit_f32(buf, m.descender)?;
    writeln!(buf, ",")?;

    write!(buf, "    encoding_scheme: Cow::Borrowed(")?;
    emit_str_literal(buf, &m.encoding_scheme)?;
    writeln!(buf, "),")?;

    writeln!(buf, "    character_metrics: Cow::Borrowed({ident}_CHARS),")?;
    writeln!(buf, "    kerning_pairs: Cow::Borrowed({ident}_KERNS),")?;

    writeln!(buf, "}};\n")?;
    Ok(())
}

fn find_width(m: &adobe_font_metrics::FontMetrics<'_>, name: &str) -> Option<f32> {
    m.character_metrics
        .iter()
        .find(|c| c.name == name)
        .map(|c| c.width_x)
}

/// Emits an f32 literal with an `_f32` suffix, using the shortest
/// round-trippable decimal representation. Special-cases `0.0` /
/// `-0.0` so signed zero round-trips deterministically.
fn emit_f32(buf: &mut String, v: f32) -> Result<(), std::fmt::Error> {
    if v == 0.0_f32 {
        // `{:?}` on signed zero prints "-0.0" / "0.0" already, but
        // routing through this branch keeps the suffix attachment
        // consistent regardless of formatter behaviour.
        if v.is_sign_negative() {
            return write!(buf, "-0.0_f32");
        }
        return write!(buf, "0.0_f32");
    }
    // `{:?}` always produces a decimal point or exponent for finite
    // non-zero f32, so `_f32` attaches to a valid float literal.
    // Wrap negative literals in parentheses so the suffix attaches
    // to the magnitude rather than (visually) to the operand of a
    // bare unary minus — `(-225.0_f32)` is unambiguous.
    if v.is_sign_negative() {
        write!(buf, "(-{:?}_f32)", -v)
    } else {
        write!(buf, "{v:?}_f32")
    }
}

/// Emits a `"..."` string literal with `\` and `"` escaped. AFM glyph
/// names and family names are restricted to ASCII identifiers in
/// practice; the escaping is defensive against any odd character
/// that might appear in `FullName`/`Weight`/`EncodingScheme`.
fn emit_str_literal(buf: &mut String, s: &str) -> Result<(), std::fmt::Error> {
    buf.push('"');
    for ch in s.chars() {
        match ch {
            '\\' => buf.push_str("\\\\"),
            '"' => buf.push_str("\\\""),
            '\n' => buf.push_str("\\n"),
            '\r' => buf.push_str("\\r"),
            '\t' => buf.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                write!(buf, "\\u{{{:x}}}", c as u32)?;
            }
            c => buf.push(c),
        }
    }
    buf.push('"');
    Ok(())
}
