[package]
name                   = "mosaic-lsp"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
description            = "Language server for Mosaic (manifest §17)."
readme.workspace       = true
homepage.workspace     = true
repository.workspace   = true
license.workspace      = true
keywords.workspace     = true
categories.workspace   = true

[[bin]]
name = "mos-lsp"
path = "src/main.rs"

[dependencies]
mosaic-core  = { workspace = true }
mosaic-parse = { workspace = true }

[lints]
workspace = true
