[package]
name                 = "adobe-font-metrics"
version.workspace    = true
edition.workspace    = true
rust-version         = "1.85"
description          = "Pure-Rust, zero-dependency parser for Adobe Font Metrics (AFM) v4.x."
readme               = "README.md"
homepage.workspace   = true
repository.workspace = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
include.workspace    = true
publish              = true

[lints]
workspace = true
