//! Generate the 256-entry PDF resource-name table consumed by
//! [`EmbeddedFontId::pdf_resource_name`].
//!
//! Why a build-time LUT instead of a `match` arm per variant:
//! adding a new embedded cut (e.g. future Noto CJK, color emoji,
//! additional Mono weights) needs to pick its index in
//! `pdf_resource_index` and have a name resolved automatically.
//! Indexing into a baked `[&[u8]; 256]` keeps that mechanical:
//! the table already contains `b"F0"`..=`b"F255"`, so the resolver
//! is just an array lookup.
//!
//! Generated content lives in `$OUT_DIR/resource_names.rs` and is
//! `include!`-d from `src/lib.rs`. The contract: index `n` resolves
//! to a `&'static [u8]` spelling `"Fn"` with no leading zeros.

use std::env;
use std::error::Error;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

fn main() -> Result<(), Box<dyn Error>> {
    let out_dir: PathBuf = env::var_os("OUT_DIR").ok_or("OUT_DIR not set")?.into();

    // Re-run only when this script changes; the output is fully
    // determined by build-time constants.
    println!("cargo:rerun-if-changed=build.rs");

    let mut buf = String::with_capacity(8192);
    buf.push_str("// @generated by mos-fonts/build.rs: DO NOT EDIT BY HAND.\n");
    buf.push_str("// 256-entry PDF resource-name LUT indexed by\n");
    buf.push_str("// `EmbeddedFontId::pdf_resource_index`. Indices 0..=14 are\n");
    buf.push_str("// reserved for Base14 fonts (see `mos-pdf`); embedded\n");
    buf.push_str("// cuts use 15..=255.\n");
    buf.push_str("pub(crate) const RESOURCE_NAMES: [&[u8]; 256] = [\n");
    for n in 0u32..=255 {
        writeln!(buf, "    b\"F{n}\",")?;
    }
    buf.push_str("];\n");

    fs::write(out_dir.join("resource_names.rs"), buf)?;
    Ok(())
}
