[package]
name                   = "mosaic-pdf"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
description            = "PDF backend for Mosaic (manifest §21.1)."
readme.workspace       = true
homepage.workspace     = true
repository.workspace   = true
license.workspace      = true
keywords.workspace     = true
categories.workspace   = true

[dependencies]
mosaic-core   = { workspace = true }
mosaic-fonts  = { workspace = true }
mosaic-layout = { workspace = true }

pdf-writer = { workspace = true }

[lints]
workspace = true
