use crate::resources;
use crate::{Base14Font, EmbeddedFont};

/// A renderable font -- either one of the Adobe Core 14 (no data
/// embedded; outlines from the PDF reader) or a bundled TrueType
/// cut (data embedded, subset per-document).
///
/// # Examples
///
/// ```
/// use mos_fonts::{Base14Font, Font};
///
/// let font = Font::Base14(Base14Font::Helvetica);
///
/// assert_eq!(font.pdf_base_name(), "Helvetica");
/// ```
#[derive(Copy, Clone, Eq, PartialEq, Debug, Hash)]
pub enum Font {
    /// A Base14 face. Layout uses AFM metrics; PDF emit uses
    /// `WinAnsiEncoding` + per-document `/Differences`.
    Base14(Base14Font),
    /// A bundled embedded face. Layout uses `rustybuzz` shaping;
    /// PDF emit produces a Type 0 CID font with `/ToUnicode`.
    Embedded(EmbeddedFontId),
}

/// Stable identifier for each bundled embedded cut. Used as the enum
/// payload of [`Font::Embedded`] so [`Font`] stays `Copy`/`Hash`/`Eq`
/// without resorting to pointer identity.
///
/// The crate ships three bundled families today: Noto Sans (four style
/// cuts -- `Regular`/`Bold`/`Italic`/`BoldItalic`) for proportional
/// body text, Noto Sans Mono (one cut -- `Mono`) for `` `raw` `` runs,
/// and Noto Sans Math (one cut -- `Math`) as the per-glyph fallback for
/// math operators when the primary face doesn't cover them. The
/// flat-enum shape is deliberate at this scale -- when a fourth family
/// lands the right move is restructuring to `{ family, cut }` rather
/// than expanding this enum variant-by-variant further.
///
/// # Examples
///
/// ```
/// use mos_fonts::EmbeddedFontId;
///
/// let id = EmbeddedFontId::Regular;
///
/// assert_eq!(id.pdf_resource_index(), 15);
/// ```
#[derive(Copy, Clone, Eq, PartialEq, Debug, Hash, Ord, PartialOrd)]
pub enum EmbeddedFontId {
    /// Noto Sans Regular.
    Regular,
    /// Noto Sans Bold.
    Bold,
    /// Noto Sans Italic.
    Italic,
    /// Noto Sans Bold Italic.
    BoldItalic,
    /// Noto Sans Mono Regular. The crate's monospace face for raw runs.
    Mono,
    /// Noto Sans Math Regular. The crate's math face -- covers
    /// `<= >= != sqrt partial sum delta diamond minus` and broader
    /// Unicode math. Used as the default fallback target on
    /// [`crate::FontFamily::noto_sans`] so math codepoints route through
    /// it when shaping yields `.notdef` against the primary face.
    Math,
}

impl EmbeddedFontId {
    /// All bundled embedded cuts in a stable order. Used by the PDF
    /// backend to enumerate `/Font` resource entries deterministically.
    pub const ALL: [Self; 6] = [
        Self::Regular,
        Self::Bold,
        Self::Italic,
        Self::BoldItalic,
        Self::Mono,
        Self::Math,
    ];

    /// Resolve to the bundled [`EmbeddedFont`] data. Initialised on
    /// first use; subsequent calls return the same `&'static` reference.
    ///
    /// # Examples
    ///
    /// ```
    /// use mos_fonts::EmbeddedFontId;
    ///
    /// let data = EmbeddedFontId::Regular.data();
    ///
    /// assert_eq!(data.postscript_name, "NotoSans");
    /// ```
    #[must_use]
    pub fn data(self) -> &'static EmbeddedFont {
        resources::embedded_font(self)
    }

    /// PDF resource-name index `n` for `Fn`. F1..F14 are reserved for
    /// the 14 Base14 fonts (see `mos-pdf`'s Base14 resource layout);
    /// embedded cuts use F15..=F255. The number is **stable per
    /// variant forever** -- never re-number for byte-stability.
    /// Adding a new bundled cut is one match arm here plus a
    /// `RESOURCE_NAMES`-table lookup; the 256-entry table in
    /// `$OUT_DIR/resource_names.rs` is generated by `build.rs` and
    /// already accommodates F20..=F255 with no per-variant churn.
    ///
    /// # Examples
    ///
    /// ```
    /// use mos_fonts::EmbeddedFontId;
    ///
    /// assert_eq!(EmbeddedFontId::Math.pdf_resource_index(), 20);
    /// ```
    #[must_use]
    pub const fn pdf_resource_index(self) -> u8 {
        match self {
            Self::Regular => 15,
            Self::Bold => 16,
            Self::Italic => 17,
            Self::BoldItalic => 18,
            Self::Mono => 19,
            Self::Math => 20,
        }
    }

    /// PDF resource name (`b"F<n>"`) for this cut. Backed by a baked
    /// `[&[u8]; 256]` LUT generated at build time so future variants
    /// only need to pick an unused index above and the name resolves
    /// automatically.
    ///
    /// # Examples
    ///
    /// ```
    /// use mos_fonts::EmbeddedFontId;
    ///
    /// assert_eq!(EmbeddedFontId::Regular.pdf_resource_name(), b"F15");
    /// ```
    #[must_use]
    pub fn pdf_resource_name(self) -> &'static [u8] {
        resources::pdf_resource_name(self)
    }
}

impl Font {
    /// All 14 Base14 faces in Mosaic's PDF-resource order (`F1`..`F14`).
    ///
    /// Page resource dictionaries always enumerate these -- even when
    /// unused -- so a Base14-only document's byte output stays stable
    /// across runs. Embedded faces are added on top, per-document.
    ///
    /// The ordering is **decoupled** from [`Base14Font::ALL`]: the
    /// four pre-existing layout faces keep their historical `F1`..`F4`
    /// resource numbers so existing integration goldens don't shift.
    pub const ALL_BASE14: [Self; 14] = [
        Self::Base14(Base14Font::Helvetica),
        Self::Base14(Base14Font::HelveticaBold),
        Self::Base14(Base14Font::HelveticaOblique),
        Self::Base14(Base14Font::Courier),
        Self::Base14(Base14Font::HelveticaBoldOblique),
        Self::Base14(Base14Font::TimesRoman),
        Self::Base14(Base14Font::TimesBold),
        Self::Base14(Base14Font::TimesItalic),
        Self::Base14(Base14Font::TimesBoldItalic),
        Self::Base14(Base14Font::CourierBold),
        Self::Base14(Base14Font::CourierOblique),
        Self::Base14(Base14Font::CourierBoldOblique),
        Self::Base14(Base14Font::Symbol),
        Self::Base14(Base14Font::ZapfDingbats),
    ];

    /// If this is a Base14 face, return the underlying variant.
    ///
    /// # Examples
    ///
    /// ```
    /// use mos_fonts::{Base14Font, Font};
    ///
    /// let font = Font::Base14(Base14Font::Courier);
    ///
    /// assert_eq!(font.base14(), Some(Base14Font::Courier));
    /// ```
    #[must_use]
    pub const fn base14(self) -> Option<Base14Font> {
        match self {
            Self::Base14(f) => Some(f),
            Self::Embedded(_) => None,
        }
    }

    /// If this is an embedded face, return its bundled id.
    ///
    /// # Examples
    ///
    /// ```
    /// use mos_fonts::{EmbeddedFontId, Font};
    ///
    /// let font = Font::Embedded(EmbeddedFontId::Bold);
    ///
    /// assert_eq!(font.embedded(), Some(EmbeddedFontId::Bold));
    /// ```
    #[must_use]
    pub const fn embedded(self) -> Option<EmbeddedFontId> {
        match self {
            Self::Embedded(id) => Some(id),
            Self::Base14(_) => None,
        }
    }

    /// PDF `/BaseFont` name for Base14 (e.g. `"Helvetica-BoldOblique"`)
    /// or the embedded face's PostScript name. The embedded path also
    /// gets a six-letter subset tag in the actual PDF emission, but that
    /// belongs to the per-document subset, not the bundled cut.
    ///
    /// # Examples
    ///
    /// ```
    /// use mos_fonts::{Base14Font, Font};
    ///
    /// let font = Font::Base14(Base14Font::HelveticaBoldOblique);
    ///
    /// assert_eq!(font.pdf_base_name(), "Helvetica-BoldOblique");
    /// ```
    #[must_use]
    pub fn pdf_base_name(self) -> &'static str {
        match self {
            Self::Base14(f) => f.pdf_base_name(),
            Self::Embedded(id) => id.data().postscript_name,
        }
    }

    /// Stable per-resource name (`F1`..`F14` for Base14, `F15`..`F20`
    /// for embedded). Page font dictionaries map these to indirect
    /// font refs.
    ///
    /// # Examples
    ///
    /// ```
    /// use mos_fonts::{Base14Font, Font};
    ///
    /// let font = Font::Base14(Base14Font::Helvetica);
    ///
    /// assert_eq!(font.pdf_resource_name(), b"F1");
    /// ```
    #[must_use]
    pub fn pdf_resource_name(self) -> &'static [u8] {
        match self {
            Self::Base14(f) => Self::Base14(f).base14_resource_name(),
            Self::Embedded(id) => id.pdf_resource_name(),
        }
    }

    /// Internal: Base14-only resource name table (`F1`..`F14`). Kept as
    /// a method on `Font` rather than on `Base14Font` so the lookup
    /// reads the same way the enum dispatch does. The `Embedded` arm
    /// is handled at the caller (`pdf_resource_name`) so this private
    /// helper never sees it.
    fn base14_resource_name(self) -> &'static [u8] {
        let Self::Base14(f) = self else {
            return b"F0";
        };
        match f {
            Base14Font::Helvetica => b"F1",
            Base14Font::HelveticaBold => b"F2",
            Base14Font::HelveticaOblique => b"F3",
            Base14Font::Courier => b"F4",
            Base14Font::HelveticaBoldOblique => b"F5",
            Base14Font::TimesRoman => b"F6",
            Base14Font::TimesBold => b"F7",
            Base14Font::TimesItalic => b"F8",
            Base14Font::TimesBoldItalic => b"F9",
            Base14Font::CourierBold => b"F10",
            Base14Font::CourierOblique => b"F11",
            Base14Font::CourierBoldOblique => b"F12",
            Base14Font::Symbol => b"F13",
            Base14Font::ZapfDingbats => b"F14",
        }
    }
}

impl From<Base14Font> for Font {
    fn from(f: Base14Font) -> Self {
        Self::Base14(f)
    }
}

impl From<EmbeddedFontId> for Font {
    fn from(id: EmbeddedFontId) -> Self {
        Self::Embedded(id)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pdf_resource_name_is_f1_through_f20() {
        for (i, font) in Font::ALL_BASE14.iter().enumerate() {
            let expected = format!("F{}", i + 1);
            assert_eq!(font.pdf_resource_name(), expected.as_bytes());
        }
        for (i, id) in EmbeddedFontId::ALL.iter().enumerate() {
            let expected = format!("F{}", 15 + i);
            assert_eq!(id.pdf_resource_name(), expected.as_bytes());
        }
    }

    #[test]
    fn font_all_base14_preserves_historical_resource_numbers() {
        assert_eq!(Font::ALL_BASE14[0], Font::Base14(Base14Font::Helvetica));
        assert_eq!(Font::ALL_BASE14[1], Font::Base14(Base14Font::HelveticaBold));
        assert_eq!(
            Font::ALL_BASE14[2],
            Font::Base14(Base14Font::HelveticaOblique)
        );
        assert_eq!(Font::ALL_BASE14[3], Font::Base14(Base14Font::Courier));
    }
}
